### ISSUE TITLE
Enhance mount parameter

### ISSUE THREAD

**Issue by JensHeinrich** [containers/ansible-podman-collections#101]
/kind feature

**Description**

Use same structure as [docker_container](https://docs.ansible.com/ansible/latest/modules/docker_container_module.html#docker-container-module) for mounts

**Additional information you deem important (e.g. issue happens only occasionally):**

This should be done now, so users can switch from docker_container to podman_container with ease (#99 )

**Changes**
- Replace mount parameter with mounts (or keep it for backwards compability)
- Parse mounts as a list of dictionaries

**Comment by jtryggveson** [comment]
I would also appreciate support for multiple mounts, either plain list or list of dicts.

**Comment by sshnaidm** [comment]
Should be fixed by #745  and #753
