### ISSUE TITLE
Cannot pip-install using poetry

### ISSUE THREAD

**Issue by Yajo** [containers/ansible-podman-collections#132]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I see you can install the collection using pip since #100. Great! I use https://python-poetry.org/ to handle my sub-collection, but it doesn't seem to see ansible podman collection if pip-installed in the venv.

**Steps to reproduce the issue:**

```bash
python3 -m venv .venv
poetry env use .venv/bin/python
poetry init
poetry add ansible
poetry add 'git+https://github.com/containers/ansible-podman-collections.git@1.3.2'
poetry run ansible-doc containers.podman.podman_container
```

**Describe the results you received:**

```
[WARNING]: module containers.podman.podman_container not found in: /var/home/yajo/.ansible/plugins/modules:/usr/share/ansible/plugins/modules:/var/home/yajo/mydevel/mando/.venv/lib64/python3.8/site-
packages/ansible/modules
```

**Describe the results you expected:**

```
> PODMAN_CONTAINER    (/var/home/yajo/mydevel/mando/collections/ansible_collections/containers/podman/plugins/modules/podman_container.py)

        Start, stop, restart and manage Podman containers

[...]
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `ansible --version`:**

```
ansible 2.9.11
  config file = /var/home/yajo/mydevel/mando/ansible.cfg
  configured module search path = ['/var/home/yajo/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /var/home/yajo/mydevel/mando/.venv/lib64/python3.8/site-packages/ansible
  executable location = /var/home/yajo/mydevel/mando/.venv/bin/ansible
  python version = 3.8.6 (default, Sep 25 2020, 00:00:00) [GCC 10.2.1 20200723 (Red Hat 10.2.1-1)]
```

**Output of `podman version`:**

```
podman version 2.1.1
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.16.1
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.21-2.fc32.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.21, commit: 81d18b6c3ffc266abdef7ca94c1450e669a6a388'
  cpus: 12
  distribution:
    distribution: fedora
    version: "32"
  eventLogger: journald
  hostname: yajolap-tecnativa-com
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.8.16-200.fc32.x86_64
  linkmode: dynamic
  memFree: 3325992960
  memTotal: 16616603648
  ociRuntime:
    name: runc
    package: runc-1.0.0-144.dev.gite6555cc.fc32.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc10+dev
      commit: fbdbaf85ecbc0e077f336c03062710435607dbf1
      spec: 1.0.1-dev
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.4-1.fc32.x86_64
    version: |-
      slirp4netns version 1.1.4
      commit: b66ffa8e262507e37fca689822d23430f3357fe8
      libslirp: 4.3.1
      SLIRP_CONFIG_VERSION_MAX: 2
  swapFree: 8373198848
  swapTotal: 8376020992
  uptime: 18h 16m 52.25s (Approximately 0.75 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /var/home/yajo/.config/containers/storage.conf
  containerStore:
    number: 2
    paused: 0
    running: 0
    stopped: 2
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.2.0-1.fc32.x86_64
      Version: |-
        fusermount3 version: 3.9.1
        fuse-overlayfs: version 1.1.0
        FUSE library version 3.9.1
        using FUSE kernel interface version 7.31
  graphRoot: /var/home/yajo/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 29
  runRoot: /run/user/1000/containers
  volumePath: /var/home/yajo/.local/share/containers/storage/volumes
version:
  APIVersion: 2.0.0
  Built: 1601494271
  BuiltTime: Wed Sep 30 20:31:11 2020
  GitCommit: ""
  GoVersion: go1.14.9
  OsArch: linux/amd64
  Version: 2.1.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-2.1.1-7.fc32.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
phyisical

**Comment by sshnaidm** [comment]
The collection is installed in `/usr/share/ansible/collections`:
https://github.com/containers/ansible-podman-collections/blob/master/setup.cfg#L25-L31
```ini
data_files =
    share/ansible/collections/ansible_collections/containers/podman/ = README.md
    share/ansible/collections/ansible_collections/containers/podman/roles/ = roles/*
    share/ansible/collections/ansible_collections/containers/podman/plugins/ = plugins/*
    share/ansible/collections/ansible_collections/containers/podman/playbooks/ = playbooks/*
    share/ansible/collections/ansible_collections/containers/podman/scripts/ = scripts/*
    share/ansible/collections/ansible_collections/containers/podman/docs/ = docs/*
    share/ansible/collections/ansible_collections/containers/podman/meta/ = meta/*

```
So you need to specify a `module-path` for `ansible-doc`:
`poetry run ansible-doc --module-path .venv/share/ansible/collections containers.podman.podman_container`
should work.

**Comment by Yajo** [comment]
I guess that'd work, but TBH I'd expect that a pip-installed collection was reachable on standard collection paths... the venv location might be different depending on how it's installed, after all...

**Comment by sshnaidm** [comment]
@Yajo standard collection path is in your `$HOME/.ansible`, and no package can be installed there.

**Comment by Yajo** [comment]
I see... I guess this is more a problem of ansible itself then. https://docs.ansible.com/ansible/latest/reference_appendices/config.html#collections-paths explains that `/usr/share/ansible/collections` is a valid default path, so I guess that globally installing this collection with pip should work, but it breaks in the venv use case. Let me open an issue there.

**Comment by Yajo** [comment]
Here it is: https://github.com/ansible/ansible/issues/72384

Let's see what they say...

**Comment by nitzmahone** [comment]
We added a feature in ansible-base 2.10 for ACD (`ansible >= 2.10`) and anyone else to do this. You just need to pip install your collection as an implicit namespace package under `ansible_collections/(ns)/(coll)` anywhere on `sys.path`, and we'll pick it up.

Rather than having a special dedicated location, we scan all `sys.path` top-level dirs at startup and append any that contain an `ansible_collections` package to the end of the collection loader list, so collections found there will be found and loaded. While we don't "recommend" installing collections this way in general (as simple packaging errors can trash other collections since they're all under the same root packages), we do take some special care at runtime to prevent collection packaging errors from DoSing other collections or Ansible itself.

**Comment by sshnaidm** [comment]
If it was a different collection which is not in ACD, I would install it to `lib/python3.7/site-packages/ansible_collections/` then, right @nitzmahone ?
But if this collection already exists there like `containers.podman`, it would overwrite one from Ansible installation, which is not a good idea.
So collections that are part of ACD I wouldn't install into this path.

**Comment by nitzmahone** [comment]
Well, you'd probably just `pip` install it to wherever pip wants to install it, but we'll respect the `sys.path` order used by the interpreter for precedence, and IIRC we explicitly ignore package init's above the collection level, so there shouldn't be any worry about packaging failures DoSing other collections.

But yes, if you're installing to the same site-packages (or whatever) as ACD did, and you overwrite an ACD-packaged collection with a discretely packaged one, the next ACD upgrade or uninstall will wreak havoc. This is one of the reasons we don't really recommend or document this as a general procedure- it's there, it's unlikely to go away, but it's also easy to make a mess and break stuff.

**Comment by nitzmahone** [comment]
ACD (as well as other OS distros that roughly track it) have considered moving to metapackages (rather than the current monolithic Python-package-of-collections)- that would arguably make that problem easier to solve, but at the cost of a lot more packaging overhead and potential difficulty with other metadata and deps inherent to a metapackage design. I'm not sure where that discussion landed, but maybe @abadger or @gundalow can shed some light.

**Comment by Yajo** [comment]
Wouldn't it make sense that ACD reads collections in this order?

1. `site-packages/ansible_collections/`
1. `site-packages/ansible_collections_core/`

This way, collection owners have a clear path where to let users pip-install their content, and ACD packagers just have to install builtin collections in a separate path that would also be available as a fallback.

If a collection was found in the 1st dir, it wouldn't be searched in the 2nd dir, so there'd be no conflict.

**Comment by abadger** [comment]
> Wouldn't it make sense that ACD reads collections in this order?
> 
>     1. `site-packages/ansible_collections/`
> 
>     2. `site-packages/ansible_collections_core/`
> 
> 
> This way, collection owners have a clear path where to let users pip-install their content, and ACD packagers just have to install builtin collections in a separate path that would also be available as a fallback.
> 
> If a collection was found in the 1st dir, it wouldn't be searched in the 2nd dir, so there'd be no conflict.

I don't think so.... That seems like it can be done with either installing to another site-packages directory or installing into another collection path.  It seems like your trying to combine both of those features instead of picking one.

The ansible-base team didn't like the idea of metapackackages of the Ansible package from pip so i said we'd revisit that idea for 2.11.(collection owners like the idea of Ansible being a metapackackage so it's a question of figuring out what the concerns are on both sides and figuring out a path that takes care of the worst problems pointed out by both).  Individual distros are looking to package the monolithic Ansible package from pip or to package individual collections depending on their own perception of their users needs.

**Comment by sshnaidm** [comment]
I think we can close this issue. Feel free to reopen if there are still questions.
