### ISSUE TITLE
Allow loading images from tarballs

### ISSUE THREAD

**Issue by W35170** [containers/ansible-podman-collections#144]
/kind feature

**Description**

Allow loading images from tarballs like docker_image plugin does.

This (https://docs.ansible.com/ansible/latest/collections/community/general/docker_image_module.html) plugin allows loading images to docker by providing a path to a tarball.

Basically, this, but in Ansible:
```
podman image load my_image.tar
```

**Comment by Gug42** [comment]
Hello,

Thank your for your works first. 
Well indeed I have the same need but sadly no real capacity to modify the plugin code.

Thank you in advance.
