### ISSUE TITLE
Add mac_address to podman_container fields

### ISSUE THREAD

**Issue by ericzolf** [containers/ansible-podman-collections#146]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

podman_container module doesn't offer the mac-address as field.

**Additional information you deem important (e.g. issue happens only occasionally):**

Without mac-address, I can't get a stable IP address through DHCP.

I attached a patched version of the module, untested yet but the change is rather straight forward:

[podman_container.py.txt](https://github.com/containers/ansible-podman-collections/files/5544501/podman_container.py.txt)

**Comment by sshnaidm** [comment]
@ericzolf thanks, why wouldn't you make PR from this file? Seems good to me.
You can [leave "Allow edits from maintainers" ](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) selected and then [any other can fix or change your patch](https://ardupilot.org/dev/docs/editing-prs.html) if you don't have a time.

**Comment by ericzolf** [comment]
I could but the difference between my version, based on the Galaxy version, and the current master version is quite huge (I guess due to "Move containers logic to module utils") is quite huge. Let's see...
