### ISSUE TITLE
add support for setting MTU in podman_network

### ISSUE THREAD

**Issue by pschiffe** [containers/ansible-podman-collections#147]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

The [CNI bridge](https://www.cni.dev/plugins/main/bridge/) plugin/driver supports setting custom MTU value, but it's not possible to set this value via containers.podman.podman_network. Please add support for MTU setting directly or via some general custom fields. Thanks!

**Comment by sshnaidm** [comment]
@pschiffe as I see it's not supported in [`podman network`](https://github.com/containers/podman/blob/master/docs/source/markdown/podman-network-create.1.md) command, so firstly it should be added there. Can you maybe add issue in [podman repo](https://github.com/containers/podman/) to support MTU?

**Comment by pschiffe** [comment]
Done! Thanks for taking a look.

https://github.com/containers/podman/issues/8454

**Comment by pschiffe** [comment]
The change has been implemented in https://github.com/containers/podman/pull/8457, waiting to be released.
The parameter is `-o, --opt` and 2 values are supported, `mtu` and `vlan`; can be used like `mtu=9000` or `vlan=9`

**Comment by sshnaidm** [comment]
@pschiffe great, thanks for the effort!
