### ISSUE TITLE
New Galaxy tag replacing the 1.3.2 version

### ISSUE THREAD

**Issue by falstaff1288** [containers/ansible-podman-collections#156]
Hello,

This is not a bug but rather a feature request.

Is there any plans to soon replace the 1.3.2 Galaxy tag for this project? 

A lot of useful features as been added since October and pulling the collection through the `ansible-galaxy` command always pull the 1.3.2 version no matter what due to the version being hardcoded in the galaxy.yml file. I would prefer to use ansible-galaxy to pull this collection rather than a `git clone`.

Thanks!

**Comment by sshnaidm** [comment]
Sure, I'll try to release today or tomorrow, after some bugfixes.

**Comment by sshnaidm** [comment]
1.4.0 is in galaxy
