### ISSUE TITLE
Support for podman-create

### ISSUE THREAD

**Issue by c-goes** [containers/ansible-podman-collections#165]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

Support for an equivalent command to `podman create`. Create a container without starting it. I tried `podman_container` with state `present` but it doesn't do what I expected.

**Comment by sshnaidm** [comment]
@c-goes you need state `stopped`. Maybe worth to add alias `created` for it.

**Comment by c-goes** [comment]
> @c-goes you need state `stopped`. Maybe worth to add alias `created` for it.

If just want to make sure the container exists. I don't want to stop it if it's running.

**Comment by sshnaidm** [comment]
> > @c-goes you need state `stopped`. Maybe worth to add alias `created` for it.
> 
> I just want to make sure the container exists. I don't want to stop it if it's running.
> In my playbook I create a systemd unit and then use systemd to manage the container.

I can think about "created" state as it's done with `podman_pod` module here:
https://github.com/containers/ansible-podman-collections/blob/90e6bc33f91f4ccee97a95fadbc676efdb338fc9/plugins/module_utils/podman/podman_pod_lib.py#L669-L675

**Comment by sshnaidm** [comment]
@c-goes please try #167 if it helps you

**Comment by c-goes** [comment]
Thanks.

**Comment by brettinternet** [comment]
Thank you for this feature. This is particularly useful with: https://podman.io/blogs/2020/12/09/podman-systemd-demo.html
