### ISSUE TITLE
Is it possible to import local images ?

### ISSUE THREAD

**Issue by Samet-MohamedAmin** [containers/ansible-podman-collections#171]
I am working in an environment without any external connection except ssh.
So I have to save images as files, then copy these files to remote server and then import image files.

Does ansible-podman-collections support importing local images (without pulling images from repositories like docker hub)?

**Comment by sshnaidm** [comment]
If you mean loading images from tarballs, we have a request for this: #144

**Comment by sshnaidm** [comment]
duplicate
