### ISSUE TITLE
create systemd unit files

### ISSUE THREAD

**Issue by Klaas-** [containers/ansible-podman-collections#18]
Hi,
I am interested in implementing systemd units for containers and especially pods, would you see that as part of podman_container or should that go into a new module?

I already looked into the podman command, I think `podman generate systemd` needs another output format for it to be easily parseable in python, but I would welcome any suggestions.

Greetings
Klaas

**Comment by sshnaidm** [comment]
@Klaas- , I think we'd better to make it as a separate module. Even if we integrate it into podman_container, it's always good to have it separately in case you need just generate files for existing containers.
You can just parse output of command, it's actually the text of systemd file, like we do here with version for example: https://github.com/containers/ansible-podman-collections/blob/master/plugins/modules/podman_container.py#L1777-L1778
```python
def _get_podman_version(self):
      # pylint: disable=unused-variable
      rc, out, err = self.module.run_command(
          [self.module.params['executable'], b'--version'])
      if rc != 0 or not out or "version" not in out:
          self.module.fail_json(msg="%s run failed!" % self.module.params['executable'])
      return out.split("version")[1].strip()
```

**Comment by Klaas-** [comment]
@sshnaidm using the stdout output works for a single container, my main focus for now is getting awx to work (and that is a pod with multiple containers). I looked at the output, that's a concatination of the multiple service files without a real seperator if I did not misread the output :) I was going to suggest to add a json output or something like that but go is not really my language :D

**Comment by sshnaidm** [comment]
@Klaas- you're right, there is no visible delimiter. We can try to rely on comments, which are first lines in the file like:
```
# pod-mypod.service
# autogenerated by Podman 1.8.1
# Wed Apr  8 22:16:40 IDT 2020
```
But it'll be a guess.
Can you point me please to pod configuration with AWX?
I'm not sure Podman team will adopt JSON for a file output, might be challenging with multiline and indentation. But for a visible and well defined delimiter I think would be reasonable to ask.

**Comment by Klaas-** [comment]
@sshnaidm I'm currently working on getting the current version to work https://github.com/ikke-t/awx_pod/pull/7 is what I'm using for now, but I want to replace the podman role with something working smoother :)

**Comment by sshnaidm** [comment]
@Klaas- hi, any work in progress about generation of systemd files?
I think to start systemd files generation for pods and containers, also play_kube functionality. I wonder if you made something or maybe have use cases for this. I think it's worth to add automatic generation of systemd units and their installation.

**Comment by Klaas-** [comment]
@sshnaidm hi, no I haven't worked on it more. For now I my primary usecase is the awx_pod and that is using https://github.com/ikke-t/podman-container-systemd - I would like to see this implemented here but I haven't found the time yet :D

**Comment by Luap99** [comment]
I have added the `--format json` option in https://github.com/containers/podman/pull/7329. This will be included in podman v2.1.
```
$ podman generate systemd --format json ad352b0cb348
{
 "container-ad352b0cb348cd28d097dae8902a444e5fca1aacd834698018aa482437b8f667": "# container-ad352b0cb348cd28d097dae8902a444e5fca1aacd834698018aa482437b8f667.service\n# autogenerated by Podman 2.1.0-dev\n# Mon Sep 14 20:26:09 CEST 2020\n\n[Unit]\nDescription=Podman container-ad352b0cb348cd28d097dae8902a444e5fca1aacd834698018aa482437b8f667.service\nDocumentation=man:podman-generate-systemd(1)\nWants=network.target\nAfter=network-online.target\n\n[Service]\nEnvironment=PODMAN_SYSTEMD_UNIT=%n\nRestart=on-failure\nExecStart=/home/paul/go/src/github.com/containers/libpod/bin/podman start ad352b0cb348cd28d097dae8902a444e5fca1aacd834698018aa482437b8f667\nExecStop=/home/paul/go/src/github.com/containers/libpod/bin/podman stop -t 10 ad352b0cb348cd28d097dae8902a444e5fca1aacd834698018aa482437b8f667\nExecStopPost=/home/paul/go/src/github.com/containers/libpod/bin/podman stop -t 10 ad352b0cb348cd28d097dae8902a444e5fca1aacd834698018aa482437b8f667\nPIDFile=/run/user/1000/containers/overlay-containers/ad352b0cb348cd28d097dae8902a444e5fca1aacd834698018aa482437b8f667/userdata/conmon.pid\nKillMode=none\nType=forking\n\n[Install]\nWantedBy=multi-user.target default.target\n"
}
```

**Comment by diggnsaegg** [comment]
any updates here? Right now I'm using the shell module to create systemd files.

**Comment by soulmanos** [comment]
I'd be keen for this functionality too, likewise using shell

**Comment by sshnaidm** [comment]
This is an open source project, you're welcome to send a patch.
