### ISSUE TITLE
podman_image doesn't authenticate when doing pull

### ISSUE THREAD

**Issue by nomadcz** [containers/ansible-podman-collections#219]
/kind bug

**Description**
podman_image doesn't authenticate when doing pull

**Steps to reproduce the issue:**

```
   - name: Pull ansible image
     podman_image:
       username: 'user'
       password: 'password'
       name: my.repo/ansible29
       tag: 2.9.17
       validate_certs: false
```

**Describe the results you received:**
Failed to pull image my.repo/ansible29:2.9.17

**Describe the results you expected:**
Image properly pulled from repo

**Additional information you deem important (e.g. issue happens only occasionally):**
For some reason "pull" pretty much ignores provided credentials.
Adding following (copy paste from push) into "pull" function works

```
        if self.username and self.password:
            cred_string = '{user}:{password}'.format(user=self.username, password=self.password)
            args.extend(['--creds', cred_string])
```

**Version of the `containers.podman` collection:**
**Either git commit if installed from git: `git show --summary`**
**Or version from `ansible-galaxy` if installed from galaxy: `ansible-galaxy collection list | grep containers.podman`**

```
(paste your output here)
```

**Output of `ansible --version`:**

```
ansible 2.9.17
  config file = /srv/data/prod/ansible/core/remote/cm/environments/pred/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Aug 18 2020, 08:33:21) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]

```

**Output of `podman version`:**

```
podman version 2.0.5

```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Playbok you run with ansible (e.g. content of `playbook.yaml`):**

```
(paste your output here)
```

**Command line and output of ansible run with high verbosity**

**Please NOTE: if you submit a bug about idempotency, run the playbook with `--diff` option, like:**

`ansible-playbook -i inventory --diff -vv playbook.yml`

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
RHEL 8.3

**Comment by nomadcz** [comment]
So it seems fix is already included here in the repo. So I guess I just have to wait for RedHat to include fixed version in RHEL8.

**Comment by sshnaidm** [comment]
@nomadcz for a newer version of this collection you just need to install a newer version from Galaxy:
 `ansible-galaxy collection install --force containers.podman`
