### ISSUE TITLE
Idempotency issue for networks involving IPv6 address shortening

### ISSUE THREAD

**Issue by waweber** [containers/ansible-podman-collections#224]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Podman networks can be non-idempotent because a diff occurs when using shortened/non-shortened IPv6 addresses

**Steps to reproduce the issue:**

1. Create a network with ipv6 enabled, using the subnet e.g. fd4f:552c:830f:0000::/64
2. Re-run the play

**Describe the results you received:**

The network is recreated. The issue is straightforward, the module is considering `fd4f:552c:830f::/64` different than `fd4f:552c:830f:0000::/64`, but they are semantically the same. The fix should be straightforward too, instead of treating them as strings, parse it with the Python module `ipaddress.ip_network` and compare those objects.

**Describe the results you expected:**

The play should pass ok

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version of the `containers.podman` collection:**

```
1.4.5-dev
```

**Output of `ansible --version`:**

```
ansible 2.10.5
```

**Output of `podman version`:**

```
podman version 3.0.0-dev
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.19.2
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.25-1.module_el8.4.0+673+eabfc99d.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.25, commit: 897f4ebd69b9e9c725621fabf1d7c918ef635a68'
  cpus: 1
  distribution:
    distribution: '"centos"'
    version: "8"
  eventLogger: file
  hostname: localhost.localdomain
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 4.18.0-240.15.1.el8_3.centos.plus.x86_64
  linkmode: dynamic
  memFree: 62443520
  memTotal: 1016270848
  ociRuntime:
    name: crun
    package: crun-0.17-1.module_el8.4.0+673+eabfc99d.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.17
      commit: 0e9229ae34caaebcb86f1fde18de3acaf18c6d9a
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    selinuxEnabled: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.8-1.module_el8.4.0+641+6116a774.x86_64
    version: |-
      slirp4netns version 1.1.8
      commit: d361001f495417b880f20329121e3aa431a8f90f
      libslirp: 4.3.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.1
  swapFree: 2143285248
  swapTotal: 2147479552
  uptime: 1h 28m 15.85s (Approximately 0.04 days)
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /home/vagrant/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.4.0-2.module_el8.4.0+673+eabfc99d.x86_64
      Version: |-
        fusermount3 version: 3.2.1
        fuse-overlayfs: version 1.4
        FUSE library version 3.2.1
        using FUSE kernel interface version 7.26
  graphRoot: /home/vagrant/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 0
  runRoot: /run/user/1000/containers
  volumePath: /home/vagrant/.local/share/containers/storage/volumes
version:
  APIVersion: 3.0.0
  Built: 1612303593
  BuiltTime: Tue Feb  2 22:06:33 2021
  GitCommit: ""
  GoVersion: go1.15.7
  OsArch: linux/amd64
  Version: 3.0.0-dev
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-3.0.0-0.33rc2.module_el8.4.0+673+eabfc99d.x86_64
```

**Playbok you run with ansible (e.g. content of `playbook.yaml`):**

```
- name: Create example
      containers.podman.podman_network:
        name: example
        ipv6: yes
        subnet: fd4f:552c:830f:0000::/64
        state: present

```

**Command line and output of ansible run with high verbosity**

Here's the diff

```
--- before
+++ after
@@ -1 +1 @@
-subnet - fd4f:552c:830f::/64
+subnet - fd4f:552c:830f:0000::/64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Running in a test vm in Vagrant

**Comment by sshnaidm** [comment]
I'd rather not to add additional dependency for the module. I don't see any point in specifying address as `fd4f:552c:830f:0000::/64`, while you can use an usual ipv6 form `fd4f:552c:830f::/64`.

**Comment by waweber** [comment]
@sshnaidm the `ipaddress` module is a builtin that has been provided with Python since version 3.3.

If the correct behavior isn't going to be implemented, then the documentation should be updated to clearly indicate that the user must shorten IPv6 addresses in all ways possible. For example, even the "normal" looking address `fd4f:7b14:01b0:6d66::/64` results in a change when a user would reasonably expect it to work:

```
--- before
+++ after
@@ -1 +1 @@
-subnet - fd4f:7b14:1b0:6d66::/64
+subnet - fd4f:7b14:01b0:6d66::/64
```

**Comment by sshnaidm** [comment]
We still support py2, but actually we can make "best effort" here, if `ipaddress` is importable, then do shorten, if not - just ignore it Reopening

**Comment by waweber** [comment]
For something that works in both Python 2 and 3, you can do `import socket; socket.inet_ntop(socket.AF_INET6, socket.inet_pton(socket.AF_INET6, "fd00:ab:00::1"))` which will return the shortened string for any input ipv6 address. However, the CIDR notation has to be split out first.

**Comment by sshnaidm** [comment]
That's interesting workaround, but let's keep it simpler. Python 2 support will go eventually.
