### ISSUE TITLE
podman_network ipv6=no doesn't seem to work

### ISSUE THREAD

**Issue by dsedivec** [containers/ansible-podman-collections#249]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

podman_network `ipv6=no` seems to pass `--ipv6` to e.g. `podman network create`.

**Steps to reproduce the issue:**

1. `ansible -m containers.podman.podman_network -a 'state=present name=testnet0 ipv6=no' somehost`

**Describe the results you received:**

```
somehost | FAILED! => {
    "changed": false,
    "msg": "Can't create network testnet0",
    "stderr": "Error: ipv6 option requires an IPv6 --subnet to be provided\n",
    "stderr_lines": [
        "Error: ipv6 option requires an IPv6 --subnet to be provided"
    ],
    "stdout": "",
    "stdout_lines": []
}
```

**Describe the results you expected:**

`testnet0` to be created without IPv6.

**Additional information you deem important (e.g. issue happens only occasionally):**

Seems like all other boolean options taken by `podman_network` are either passed like [`--internal=false`][0] or [not directly converted to `podman network` options at all][1].  I imagine `addparam_ipv6` needs to actually test `self.params['ipv6']` to know whether or not to put `--ipv6` on the command line.

(BTW, I guess Podman networks are *never* IPv6 by default, since there doesn't seem to be a `--ipv6=false` or `--no-ipv6`?)

[0]: https://github.com/containers/ansible-podman-collections/blob/ecc02870df6be7e3841bb5d191938b5e5c5db587/plugins/modules/podman_network.py#L252
[1]: https://github.com/containers/ansible-podman-collections/blob/ecc02870df6be7e3841bb5d191938b5e5c5db587/plugins/modules/podman_network.py#L627-L628

**Version of the `containers.podman` collection:**
**Either git commit if installed from git: `git show --summary`**
**Or version from `ansible-galaxy` if installed from galaxy: `ansible-galaxy collection list | grep containers.podman`**

```
$ ansible-galaxy collection list | grep containers.podman
containers.podman             1.5.0
```

**Output of `ansible --version`:**

```
$ ansible --version
ansible 2.10.8
  config file = None
  configured module search path = ['/Users/dale/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/dale/.vpy/3.9/lib/python3.9/site-packages/ansible
  executable location = /Users/dale/.vpy/3.9/bin/ansible
  python version = 3.9.4 (default, Apr  6 2021, 12:18:31) [Clang 12.0.0 (clang-1200.0.32.29)]
```

**Output of `podman version`:**

```
# podman version
Version:      3.1.2
API Version:  3.1.2
Go Version:   go1.16
Built:        Thu Apr 22 06:11:28 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
# podman info --debug
host:
  arch: amd64
  buildahVersion: 1.20.1
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.27-2.fc34.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.27, commit: '
  cpus: 8
  distribution:
    distribution: fedora
    version: "34"
  eventLogger: journald
  hostname: somehost
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.11.13-300.fc34.x86_64
  linkmode: dynamic
  memFree: 352141312
  memTotal: 16676921344
  ociRuntime:
    name: runc
    package: runc-1.0.0-377.rc93.fc34.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc93
      commit: 48389904331fdebba5e2db73147c067560a51d80
      spec: 1.0.2-dev
      go: go1.16
      libseccomp: 2.5.0
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    selinuxEnabled: true
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 17178550272
  swapTotal: 17179860992
  uptime: 15h 8m 5.52s (Approximately 0.62 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 1
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageStore:
    number: 6
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 3.1.2
  Built: 1619097088
  BuiltTime: Thu Apr 22 06:11:28 2021
  GitCommit: ""
  GoVersion: go1.16
  OsArch: linux/amd64
  Version: 3.1.2
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
# rpm -q podman
podman-3.1.2-1.fc34.x86_64
```

**Playbok you run with ansible (e.g. content of `playbook.yaml`):**

See above one-off Ansible command.

**Command line and output of ansible run with high verbosity**

**Please NOTE: if you submit a bug about idempotency, run the playbook with `--diff` option, like:**

`ansible-playbook -i inventory --diff -vv playbook.yml`

```
$ ansible -m containers.podman.podman_network -a 'state=present name=testnet0 ipv6=no' -vv somehost
ansible 2.10.8
  config file = /Users/dale/x/ansible.cfg
  configured module search path = ['/Users/dale/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/dale/.vpy/3.9/lib/python3.9/site-packages/ansible
  executable location = /Users/dale/.vpy/3.9/bin/ansible
  python version = 3.9.4 (default, Apr  6 2021, 12:18:31) [Clang 12.0.0 (clang-1200.0.32.29)]
Using /Users/dale/x/ansible.cfg as config file
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.
META: ran handlers
somehost | FAILED! => {
    "changed": false,
    "msg": "Can't create network testnet0",
    "stderr": "Error: ipv6 option requires an IPv6 --subnet to be provided\n",
    "stderr_lines": [
        "Error: ipv6 option requires an IPv6 --subnet to be provided"
    ],
    "stdout": "",
    "stdout_lines": []
}
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical machine running Fedora 34-ish

**Comment by sshnaidm** [comment]
Why do you pass `no` to `ipv6`? What are you trying to achieve?

**Comment by dsedivec** [comment]
> Why do you pass `no` to `ipv6`? What are you trying to achieve?

I passed `ipv6=no` because it is listed as a boolean option and I wanted to make sure that IPv6 networking would not be enabled.

**Comment by sshnaidm** [comment]
Please check #250 
But usually you don't need to pass `false` to `ipv6`, it's the default.

**Comment by dsedivec** [comment]
> Please check #250
> But usually you don't need to pass `false` to `ipv6`, it's the default.

Works for me.  Thanks for the fix, and for the advice!
