### ISSUE TITLE
Please rename the master branch to the main branch.

### ISSUE THREAD

**Issue by rhatdan** [containers/ansible-podman-collections#256]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

/kind feature

**Description**

**Steps to reproduce the issue:**

1.

2.

3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version of the `containers.podman` collection:**
**Either git commit if installed from git: `git show --summary`**
**Or version from `ansible-galaxy` if installed from galaxy: `ansible-galaxy collection list | grep containers.podman`**

```
(paste your output here)
```

**Output of `ansible --version`:**

```
(paste your output here)
```

**Output of `podman version`:**

```
(paste your output here)
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Playbok you run with ansible (e.g. content of `playbook.yaml`):**

```
(paste your output here)
```

**Command line and output of ansible run with high verbosity**

**Please NOTE: if you submit a bug about idempotency, run the playbook with `--diff` option, like:**

`ansible-playbook -i inventory --diff -vv playbook.yml`

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by rhatdan** [comment]
@sshnaidm Could you rename the master branch to the main branch, we want all of containers repos to fix this.

**Comment by sshnaidm** [comment]
@rhatdan sure, just got a lot on the plate recently

**Comment by ssbarnea** [comment]
Doing that rename is quite easy these days, GH did most of the things, even the git client knows about that. You only need to grep for `master` inside the repository after doing the rename to spot additional changes needed.

**Comment by nishipy** [comment]
Hi @sshnaidm, if you don't mind, can I work on this? It looks higher priority than others.
https://github.com/github/renaming

**Comment by sshnaidm** [comment]
@nishipy hey, I don't mind of course, but this requires my involvement as repo owner, not something others can do. So I'll ping you when I'm available and have some time and we can do it together. :handshake:

**Comment by nishipy** [comment]
Sure thanks! Then, I'll begin with grep master and identifying files required to be revised.
