### ISSUE TITLE
Update documentation for generate_systemd

### ISSUE THREAD

**Issue by zephyros-dev** [containers/ansible-podman-collections#317]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Currently generate_systemd configuration documentation on ansible site [here](https://docs.ansible.com/ansible/latest/collections/containers/podman/podman_container_module.html#parameter-generate_systemd/file) has a **file** options which specify the location of the generated systemd file. I found that in the current version integration test [here](https://github.com/containers/ansible-podman-collections/pull/310/files#diff-0d9e1d95b16c8d097856b6e4ad1d341e3a93ad4f1f83fafd90e88f94c7d150a7) and in the current docstring [here](https://github.com/containers/ansible-podman-collections/blob/8d48e30721c1164596d6eee3e0f460df526624b4/plugins/modules/podman_pod.py#L80), the options is actually **path**.

**Comment by sshnaidm** [comment]
Unfortunately there is nothing to do but wait. Ansible docs will be updated in their schedule. If you want to use latest docs, you can use the `devel` version: https://docs.ansible.com/ansible/devel/collections/containers/podman/podman_container_module.html#parameter-generate_systemd/path
