### ISSUE TITLE
--new options for generate_systemd

### ISSUE THREAD

**Issue by zephyros-dev** [containers/ansible-podman-collections#318]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

podman generate systemd command has a [--new flag](https://docs.podman.io/en/latest/markdown/podman-generate-systemd.1.html#new) that allow the systemd to run the container from scratch instead of running an existing container. I use this feature mainly for the integration with [podman auto-update](https://docs.podman.io/en/latest/markdown/podman-auto-update.1.html), since the auto-update will recreate the container from scratch based on the systemd file.

**Comment by lbeltrame** [comment]
It's more a bug than a feature, at this point. If you specify `rm` to generate new containers at each run and you couple it with `generate_systemd`, you'll get wrong units generated, which will not behave as expected if started.

**Comment by zephyros-dev** [comment]
@sshnaidm for the use case of --new flag you can check my original feature request. For the remove options, I think by the description @lbeltrame it sounds closer to recreate. Or maybe it's auto_remove?
For the interaction with podman, the --new systemd file will create a completely new container with identical settings if you do not specify the container name ([Reference in podman documentation](https://docs.podman.io/en/latest/markdown/podman-generate-systemd.1.html#use-systemctl-to-perform-operations-on-generated-installed-unit-files)). But since the ansible podman module create the container based on the name, I'm not sure how the interaction will go.

**Comment by sshnaidm** [comment]
@lbeltrame @zephyros-dev that's what concerns me, do you have an example task and desired output? I don't understand what is expected from `--new` option in the current `podman_container` module. It seems like an option for a separate `podman_systemd_generate` module or whatever it's called. Maybe we need this one instead?

**Comment by zephyros-dev** [comment]
For example, say I have a container like this:
```
- name: HTTP Echo Container
  containers.podman.podman_container:
    name: "echo-test"
    image: "mendhak/http-https-echo:latest"
    generate_systemd:
      path: "/home/username/.config/systemd/user"
      new: yes
    state: "started"
```
My expected output would be: When I specify the new options in generate_systemd, it would run the container and create the systemd file. Idempotent wise, when I rerun the playbook with the same settings, I would expect it not to change, along with the systemd file.
I do think that it's a bit problematic if I change the state into absent after the systemd file is created. User may expect the container to be destroyed, but since the systemd create a whole new container, it will be recreated even after the state is changed into absent. Since the container lifecycle is now controlled by systemd, I do think it's out of scope for the module, but we should still put a note telling the user to stop the systemd service before putting the container state into absent.

**Comment by lbeltrame** [comment]
I meant `rm`, sorry. What I noticed is that I set my containers to remove after closing (to use podman's auto update image feature), but then the generated systemd units failed to start / restart, because they assumed the container would be there (and instead it was not, because it was removed after stopping).

**Comment by sshnaidm** [comment]
FWIW it's not breaking anything, I'm still confused what are use cases, but if it helps you - I'm totally fine to merge it. The only thing I'd add - it's tests, probably it can shed some light on its usage.
Fell free to add another PR with tests or/and examples.
