### ISSUE TITLE
Parameter ports is missing in parameter section of podman_pod_module.html

### ISSUE THREAD

**Issue by Tronde** [containers/ansible-podman-collections#329]
/kind bug

**Description**
 
The documentation shows an example, using the parameter 'ports'. This parameter is not mentioned in the parameter section.

Please add the parameter with a description to the section.

**Comment by sshnaidm** [comment]
Parameter `ports` is an alias to parameter `publish`:

https://github.com/containers/ansible-podman-collections/blob/a0377fbd240f39d35c8b833b1f961c61b445fc1b/plugins/modules/podman_container.py#L608-L620
