### ISSUE TITLE
generate_systemd does not generate systemd when path is not set

### ISSUE THREAD

**Issue by pookey** [containers/ansible-podman-collections#335]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

This is a documentation issue where the default behaviour is ambiguous. 

**Steps to reproduce the issue:**

1. set generate_systemd, but exclude path.

**Describe the results you received:**

no action.

**Describe the results you expected:**

Either documentation should make it clear that systemd isn't generated, or path should have a default.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version of the `containers.podman` collection:**
**Either git commit if installed from git: `git show --summary`**
**Or version from `ansible-galaxy` if installed from galaxy: `ansible-galaxy collection list | grep containers.podman`**

```
containers.podman 1.8.2
```

**Output of `ansible --version`:**

```
ansible [core 2.11.4]
  config file = /Users/pookey/.ansible.cfg
  configured module search path = ['/Users/pookey/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/Cellar/ansible/4.5.0/libexec/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/pookey/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.9.7 (default, Sep  3 2021, 04:31:11) [Clang 12.0.5 (clang-1205.0.22.9)]
  jinja version = 3.0.1
  libyaml = True```

**Output of `podman version`:**

```
Version:      3.2.3
API Version:  3.2.3
Go Version:   go1.15.14
Built:        Thu Sep 23 22:22:19 2021
OS/Arch:      linux/amd64
```

**Comment by zephyros-dev** [comment]
Where the systemd lies depends on whether you want to run the service as user (~/.config/systemd/user/) or as system (/etc/systemd/system/), so I think this should be left to the user to decide where they want to put their systemd file. I do think the doc could be clearer on this matter though. I'm planning on updating the doc elsewhere too so I'll add this one.

**Comment by pookey** [comment]
I agree on all of your points :)

Thanks!
