### ISSUE TITLE
podman_container is not idemponent

### ISSUE THREAD

**Issue by amenzhinsky** [containers/ansible-podman-collections#353]
ansible 5.0.1 
podman 3.4.2

I use a very simple task to create a container, the first run successfully creates it and the second produces changes that are not expected:

```
--- before
+++ after
@@ -1 +1 @@
-log_driver - journald
+log_driver - k8s-file
```

Logging configuration after both runs remain the same:
```
podman inspect -f '{{json .HostConfig.LogConfig}}' mycontainer
{"Type":"journald","Config":null,"Path":"","Tag":"","Size":"0B"}
```

My current workaround is `log_driver: journald`

**Comment by sshnaidm** [comment]
it was fixed in #340
