### ISSUE TITLE
pod: support for volumes

### ISSUE THREAD

**Issue by daynyxx** [containers/ansible-podman-collections#395]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

With the release of podman 4.0 ```podman pod create``` now supports the [--volume](https://docs.podman.io/en/latest/markdown/podman-pod-create.1.html#volume-v-source-volume-host-dir-container-dir-options) option to allow volume mounts for whole pod at a time.

**Describe the results you expected:**

I expect this would work the same as volume mounts currently work for containers.

**Comment by nishipy** [comment]
Hi, I'd like to look into this if none is working on it.

**Comment by nishipy** [comment]
According to here, is this already implemented?
https://github.com/containers/ansible-podman-collections/blob/master/plugins/modules/podman_pod.py#L329-L336

**Comment by sshnaidm** [comment]
@nishipy @daynyxx - yes, I think it's there: 
https://github.com/containers/ansible-podman-collections/blob/bf67c7e0788758be4cac090c02be2eec01de3afe/plugins/module_utils/podman/podman_pod_lib.py#L252-L256
