### ISSUE TITLE
podman_load failing on inspect when multiple images present in archive

### ISSUE THREAD

**Issue by MasterWaldo** [containers/ansible-podman-collections#411]
**Description**
Having multiple images in the archive file is causing the inspect step to fail due to 'invalid reference format'. It appears to be reading all the image names in as one long string.  `podman inspect` works with multiple images, but only if they are separated by whitespace

**Steps to reproduce the issue:**

1. Create a tarball archive with multiple images. Ex: `podman save -o image.tar busybox alpine`

2. Use `containers.podman.podman_load` to attempt to load the images. 
My playbook:
```
- hosts: workbox
  tasks:
    - containers.podman.podman_load:
        input: /tmp/images.tar
```
**Describe the results you received:**
The images are correctly loaded, but Ansible returns a failure

TASK [containers.podman.podman_load] ****************************************************************************************************************************************************
fatal: [workbox]: FAILED! => {"changed": false, "msg": "Image localhost/redis:latest,docker.io/library/python:latest inspection failed: Error: error inspecting object: invalid reference format\n"}

**Describe the results you expected:**
Ansible returns success if the image(s) successfully load

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version of the `containers.podman` collection:**
1.9.0 and 1.9.3
```
**Output of `ansible --version`:**
```
ansible [core 2.12.1]
  config file = None
  configured module search path = ['/home/cheesypanda/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/cheesypanda/.local/lib/python3.9/site-packages/ansible
  ansible collection location = /home/cheesypanda/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/cheesypanda/.local/bin/ansible
  python version = 3.9.7 (default, Sep 10 2021, 14:59:43) [GCC 11.2.0]
  jinja version = 3.0.3
  libyaml = True
```
**Output of `podman version`:**

```
Version:      3.3.1
API Version:  3.3.1
Go Version:   go1.15.14
Built:        Mon Aug 30 15:46:46 2021
OS/Arch:      linux/amd64

```
Also seen on  3.4.2

**Additional environment details (AWS, VirtualBox, physical, etc.):**
vSphere

**Comment by MasterWaldo** [comment]
I believe the issue is at line 156 in plugins/modules/podman_load.py. 
`image_name = image_name_line.split(":", maxsplit=1)[1].strip()`

The podman output for a multiple image archive looks like this:
`Loaded image(s): localhost/redis:latest,docker.io/library/python:latest`
The line of code is splitting on the first colon and stopping, so the image list is treated as one string. If it is then split on commas, or the commas swapped out for spaces, I think it should work

**Comment by sshnaidm** [comment]
@MasterWaldo would you like to submit a fix?

**Comment by MasterWaldo** [comment]
> @MasterWaldo would you like to submit a fix?

Sure I can take a crack at it

**Comment by sshnaidm** [comment]
@zyphermonkey are you using Python 2.7? It's error from py2.

**Comment by zyphermonkey** [comment]
Yes we're currently use ansible tower on rhel7 and it's basically locked to python2.

**Comment by sshnaidm** [comment]
@zyphermonkey OK, will look into it, please open a different issue for that.

**Comment by sshnaidm** [comment]
@zyphermonkey removed `maxplit` from there, should be ok for Python2 now.

**Comment by rafaelrezend** [comment]
I think the analysis and the fix might be wrong...
As I can see, @MasterWaldo is using an old version of Podman (3.3.1). In Podman 4.1.1, the output for multiple images is different:

```
[admin_app@vmc docker-images]$ podman version
Client:       Podman Engine
Version:      4.1.1
API Version:  4.1.1
Go Version:   go1.17.7
Built:        Mon Jul 11 16:56:53 2022
OS/Arch:      linux/amd64
```

Creating the tarball
`[admin_app@vmc docker-images]$ podman save -o mix.tar releases-docker.jfrog.io/jfrog/artifactory-pro:7.41.7 registry.access.redhat.com/ubi8/pause:8.6-19`

Loading the tarball (+relevant output)
```
[admin_app@vmc docker-images]$ podman load -i mix.tar
Getting image source signatures
...
Storing signatures
Loaded image: registry.access.redhat.com/ubi8/pause:8.6-19
Loaded image: releases-docker.jfrog.io/jfrog/artifactory-pro:7.41.7
```

See, Podman 4.1.1 outputs multiple `Loaded image:` strings instead of a single `Loaded image(s):`.

At first I thought the implementation for multiple images broke my use case of single images.
Then, according to the output above, it seems that it broke compatibility with Podman 4.x

@sshnaidm how to proceed here? New issue or rework this one?

**Comment by sshnaidm** [comment]
@rafaelrezend please open a new issue, so we don't miss it.
