### ISSUE TITLE
Inconsistent podman_container and podman_pod syntax - network attribute

### ISSUE THREAD

**Issue by MrSuicideParrot** [containers/ansible-podman-collections#414]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**
The podman_container module has the attribute [network](https://docs.ansible.com/ansible/latest/collections/containers/podman/podman_container_module.html#parameter-network) as a list of strings. The podman_pod has the same attribute [network](https://docs.ansible.com/ansible/latest/collections/containers/podman/podman_pod_module.html#parameter-network) as a string. In the case of pods, if we want to specify multiple networks we have to concatenate them with a comma. This causes incoherence in the API, at the same time is not normal to have this kind of syntax (comma separated strings) in ansible.

**Describe the results you expected:**
I expected that both parameters would be a list of strings.

**Comment by sshnaidm** [comment]
Sounds reasonable, would you like to send a patch?

**Comment by MrSuicideParrot** [comment]
Yes, I can do it.
