### ISSUE TITLE
Support of podman v4 network

### ISSUE THREAD

**Issue by sebastien-coavoux** [containers/ansible-podman-collections#429]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

Podman v4 has a new backend type and the output of podman network inspect is different than previously

Here is a snippet of 
```
podman network inspect podman
[
     {
          "name": "podman",
          "id": "2f259bab93aaaaa2542ba43ef33eb990d0999ee1b9924b557b7be53c0b7a1bb9",
          "driver": "bridge",
          "network_interface": "podman0",
          "created": "2022-05-20T17:42:50.467132813Z",
          "subnets": [
               {
                    "subnet": "10.88.0.0/16",
                    "gateway": "10.88.0.1"
               }
          ],
          "ipv6_enabled": false,
          "internal": false,
          "dns_enabled": true,
          "ipam_options": {
               "driver": "host-local"
          }
     }
]
```

Right now when using containers.podman.podman_network module, it will try to recreate the podman network (which is forbidden in v4)
because the diff function are based on the old structure of podman network 

Example with the dns plugin : https://github.com/containers/ansible-podman-collections/blob/master/plugins/modules/podman_network.py#L327

info is populated by get_info, which runs the command : https://github.com/containers/ansible-podman-collections/blob/master/plugins/modules/podman_network.py#L469

And overall the struct described here is different : https://github.com/containers/ansible-podman-collections/blob/master/plugins/modules/podman_network.py#L116

I believe both version / structure should be supported so maybe a v4 of the module is a good way forward to not break compatibility ?

Let me know what you think I might be able to add it.

**Comment by sshnaidm** [comment]
I think we need still to support version 3.x because version 4 is not present on all systems.

**Comment by kristvanbesien** [comment]
So this is why on my system the networks get recreated every time. 

So both podman 4.x and 3.x need to be supported...

**Comment by tazerdev** [comment]
I'm hitting this as well in v4. I don't have a way of enabling DNS on the default network in an idempotent fashion using ansible. It would be a welcome enhancement.
