### ISSUE TITLE
generate_systemd: After= and more options

### ISSUE THREAD

**Issue by dada513** [containers/ansible-podman-collections#431]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

According to the [generate-systemd manpage](https://docs.podman.io/en/latest/markdown/podman-generate-systemd.1.html), the After= option can be specified to describe dependencies of a container. 

According to [podman_container docs](https://docs.ansible.com/ansible/latest/collections/containers/podman/podman_container_module.html#parameter-generate_systemd) there is no such option for this in the ansible module.

It would be really useful to have this. For example, I can have a database container and have an app require it to be running

**Comment by brettinternet** [comment]
I recently switched to this module's `generate_systemd` option, and one of my services was unable to connect to a separate postgres container. Even after modifying the unit configuration file to include `Requires=db.service` and `After=db.service` I still had issues reconnecting on startup until I added `RestartSec=5` to give the database startup some breathing room. 🤷‍♂️ 

You may consider including the `RestartSec` option as well. In the meantime, I'll add it with the lineinfile module.
