### ISSUE TITLE
Add `podman_container_exec`  module in a similar way as docker

### ISSUE THREAD

**Issue by gsalvatella** [containers/ansible-podman-collections#480]
/kind feature

**Description**

Currently one of the most lacking features of the `containers.podman` collection is the ability to execute commands on running containers in an easy way, similarly to how the `community.docker.docker_container_exec` operates. While it seems to be possible to use the `containers.podman.podman` connection, this is in no way well documented and may not be adequate for all use cases. Add a `podman_container_exec` to fill the gap in this otherwise fantastic collection.

**Comment by nishipy** [comment]
I'll work on this
