### ISSUE TITLE
podman_image: add parameter for Containerfile location

### ISSUE THREAD

**Issue by ygabuev** [containers/ansible-podman-collections#481]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

There is a flag `-f` in `podman build ...` that specifies the location of the Containerfile to use. This is useful if the context is different from the location of the Containerfile. This flag is currently not supported by `podman.podman_image` module, the way I add this currently is via `build.extra_args` parameter.

What do you think about adding this as a first-class parameter? I could draft a PR for that, if needed.

**Comment by sshnaidm** [comment]
@ygabuev sure, go for it.

**Comment by ygabuev** [comment]
@sshnaidm added a PR [here](https://github.com/containers/ansible-podman-collections/pull/492)
