### ISSUE TITLE
podman_network always recreates network

### ISSUE THREAD

**Issue by aut0** [containers/ansible-podman-collections#483]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I added a task to create a podman network:

```
- name: Add separate Podman network if not existing
  containers.podman.podman_network:
    name: podman_net_tag_foo
    ip_range: 10.42.0.128/25
    subnet: 10.42.0.0/24
    gateway: 10.42.0.1
    recreate: no
```
Every time I run the playbook ansible recreates the network.
This is problematic when the network is added in multiple playbooks, because creating the network stops all containers on that network and then some may not come back up depending on the playbook structure.

**Steps to reproduce the issue:**

1. Create a podman_network task

2. Execute the playbook multiple times

**Describe the results you received:**

The network is recreated.

**Describe the results you expected:**

The network should not be recreated.

**Additional information you deem important (e.g. issue happens only occasionally):**

I tried debugging this a bit.
I put an exception [here](https://github.com/containers/ansible-podman-collections/blob/853d3a8cc7432aa2e48e2aaf0919c4ab9e407239/plugins/modules/podman_network.py#L594)
The condition triggers, because ```self.network.different``` is ```True```, even though the entry is the same.

**Version of the `containers.podman` collection:**
**Either git commit if installed from git: `git show --summary`**
**Or version from `ansible-galaxy` if installed from galaxy: `ansible-galaxy collection list | grep containers.podman`**

```
containers.podman             1.9.4
```

**Output of `ansible --version`:**

```
ansible [core 2.13.4]
  config file = None
  configured module search path = ['/home/lukas/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/lukas/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/lukas/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/lukas/.local/bin/ansible
  python version = 3.10.6 (main, Aug  2 2022, 00:00:00) [GCC 11.3.1 20220421 (Red Hat 11.3.1-2)]
  jinja version = 3.1.2
  libyaml = True
```

**Output of `podman version`:**

I assume on the target machine?

```
Client:       Podman Engine
Version:      4.1.1
API Version:  4.1.1
Go Version:   go1.17.10
Built:        Wed Aug  3 12:28:23 2022
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

``` yaml
host:
  arch: amd64
  buildahVersion: 1.26.2
  cgroupControllers:
  - cpuset
  - cpu
  - cpuacct
  - blkio
  - memory
  - devices
  - freezer
  - net_cls
  - perf_event
  - net_prio
  - hugetlb
  - pids
  - rdma
  cgroupManager: systemd
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.2-2.module_el8.6.0+3070+1510fbd1.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.2, commit: c442990be61228fff21b414214eaf95683cdb95c'
  cpuUtilization:
    idlePercent: 99.85
    systemPercent: 0.02
    userPercent: 0.12
  cpus: 12
  distribution:
    distribution: '"almalinux"'
    version: "8.6"
  eventLogger: file
  hostname: babbage.mwa.re
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.18.0-348.20.1.el8_5.x86_64
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 55497445376
  memTotal: 67185000448
  networkBackend: cni
  ociRuntime:
    name: runc
    package: runc-1.1.3-2.module_el8.6.0+3070+1510fbd1.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.1.3
      spec: 1.0.2-dev
      go: go1.17.10
      libseccomp: 2.5.2
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-2.module_el8.6.0+3070+1510fbd1.x86_64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.2
  swapFree: 34325131264
  swapTotal: 34325131264
  uptime: 55h 7m 5.69s (Approximately 2.29 days)
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 4
    paused: 0
    running: 4
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 1932834496512
  graphRootUsed: 9811628032
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 19
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.1.1
  Built: 1659522503
  BuiltTime: Wed Aug  3 12:28:23 2022
  GitCommit: ""
  GoVersion: go1.17.10
  Os: linux
  OsArch: linux/amd64
  Version: 4.1.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-4.1.1-2.module_el8.6.0+3070+1510fbd1.x86_64
```

**Playbok you run with ansible (e.g. content of `playbook.yaml`):**

``` yaml
 name: Deploy Odoo containers on babbage
  hosts: host.tld
  tasks:
    - name: Ping hosts
      ansible.builtin.ping:
    - name: Add separate Podman network if not existing
      containers.podman.podman_network:
        name: podman_net_tag_foo
        ip_range: 10.42.0.128/25
        subnet: 10.42.0.0/24
        gateway: 10.42.0.1
        recreate: no
    - name: Create Odoo PostgresSQL data directory
      ansible.builtin.file:
        path: /data/containers/odoo/data/postgres
        state: directory
        owner: user
        group: secret
        mode: '0755'
    - name: Create Odoo Odoo data directory
      ansible.builtin.file:
        path: /data/containers/odoo/data/odoo
        state: directory
        owner: user
        group: secret
        mode: '0755'
    - name: Create Podman pod for Odoo containers
      containers.podman.podman_pod:
        name: odoo-pod
        ip: 10.42.0.130
        network: podman_net_tag_foo
        state: started
    - name: Create PostgresSQL container for Odoo
      containers.podman.podman_container:
        name: odoo-postgres
```

**Command line and output of ansible run with high verbosity**

**Please NOTE: if you submit a bug about idempotency, run the playbook with `--diff` option, like:**

`ansible-playbook -i inventory --diff -vv playbook.yml`

```
[...]
TASK [Add separate Podman network if not existing] ******************************************************************************************
task path: /home/lukas/ansible/deploy_odoo.
--- before
+++ after
@@ -1,2 +1,2 @@
-gateway -
-subnet -
+gateway - 10.42.0.1
+subnet - 10.42.0.0/24
[...]
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

As you can see, ansible somehow gets the information that the  network changed even though it did not change. The same playbook created the network.

Any idea?

Thanks,
Lukas

**Comment by sshnaidm** [comment]
Please try to install collection from master, there were some fixes for v4. Does it help?

**Comment by aut0** [comment]
I did:
```bash
$ ansible-galaxy collection install git+https://github.com/containers/ansible-podman-collections,master
Cloning into '/home/lukas/.ansible/tmp/ansible-local-38810u3cbrhrp/tmp3ye6cy2p/ansible-podman-collectionsjube33gx'...
remote: Enumerating objects: 3171, done.
remote: Counting objects: 100% (896/896), done.
remote: Compressing objects: 100% (276/276), done.
remote: Total 3171 (delta 629), reused 756 (delta 536), pack-reused 2275
Receiving objects: 100% (3171/3171), 1.03 MiB | 4.59 MiB/s, done.
Resolving deltas: 100% (1872/1872), done.
Already on 'master'
Your branch is up to date with 'origin/master'.
Starting galaxy collection install process
Process install dependency map
Starting collection install process
Installing 'containers.podman:1.9.4' to '/home/lukas/.ansible/collections/ansible_collections/containers/podman'
Created collection for containers.podman:1.9.4 at /home/lukas/.ansible/collections/ansible_collections/containers/podman
containers.podman:1.9.4 was installed successfully

$ ansible-galaxy collection list | grep containers.podman
containers.podman 1.9.4
```
The issue persists.

**Comment by sshnaidm** [comment]
Hmm, this is weird. I've disabled idempotency for Podman v4 for `gateway` and `subnet` in https://github.com/containers/ansible-podman-collections/pull/471. So it should not even try to compare them. Please try to install collection with `--force` and check again.

**Comment by aut0** [comment]
Somthing changed, when I did:
```bash 
$ ansible-galaxy collection install --force git+https://github.com/containers/ansible-podman-collections,master
Cloning into '/home/lukas/.ansible/tmp/ansible-local-46206lb75dypm/tmp254gaa9a/ansible-podman-collectionss38dybte'...
remote: Enumerating objects: 3178, done.
remote: Counting objects: 100% (903/903), done.
remote: Compressing objects: 100% (280/280), done.
remote: Total 3178 (delta 633), reused 759 (delta 539), pack-reused 2275
Receiving objects: 100% (3178/3178), 1.03 MiB | 8.13 MiB/s, done.
Resolving deltas: 100% (1876/1876), done.
Already on 'master'
Your branch is up to date with 'origin/master'.
Starting galaxy collection install process
Process install dependency map
Starting collection install process
Installing 'containers.podman:1.9.5-dev' to '/home/lukas/.ansible/collections/ansible_collections/containers/podman'
Created collection for containers.podman:1.9.5-dev at /home/lukas/.ansible/collections/ansible_collections/containers/podman
containers.podman:1.9.5-dev was installed successfully

$ ansible-galaxy collection list | grep containers.podman
containers.podman 1.9.5-dev
```
However, the issue persists.

**Comment by sshnaidm** [comment]
@aut0 can you run please with `-vvvvv`?

**Comment by aut0** [comment]
Seems like it is related to ```disable_dns```.
When I set it to ```True``` it is somehow not rolled out and creates a change on every run.

**Comment by sshnaidm** [comment]
> Seems like it is related to `disable_dns`. When I set it to `True` it is somehow not rolled out and creates a change on every run.

So what is the task you're running? In original I don't see dns setting.

**Comment by aut0** [comment]
When I don't explicitly set ```disable_dns=True``` I always get:
```
TASK [Add separate Podman network if not existing] ******************************************************************************************
--- before
+++ after
@@ -1 +1 @@
-disable_dns - True
+disable_dns - False
```
When I set explicitly set ```disable_dns=true```, I don't get the diff.

**Comment by sshnaidm** [comment]
> When I don't explicitly set `disable_dns=True` I always get:
> 
> ```
> TASK [Add separate Podman network if not existing] ******************************************************************************************
> --- before
> +++ after
> @@ -1 +1 @@
> -disable_dns - True
> +disable_dns - False
> ```
> 
> When I set explicitly set `disable_dns=true`, I don't get the diff.

Yeah, it's because DNS is enabled by default and the module considers `disable_dns=false`. So if you don't specify DNS to be false, it will fall back to the default value. Is it disabled in your system by default somehow?
I still fails to understand how it reproduces in your env..

**Comment by aut0** [comment]
> > When I don't explicitly set `disable_dns=True` I always get:
> > ```
> > TASK [Add separate Podman network if not existing] ******************************************************************************************
> > --- before
> > +++ after
> > @@ -1 +1 @@
> > -disable_dns - True
> > +disable_dns - False
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > When I set explicitly set `disable_dns=true`, I don't get the diff.
> 
> Yeah, it's because DNS is enabled by default and the module considers `disable_dns=false`. So if you don't specify DNS to be false, it will fall back to the default value. Is it disabled in your system by default somehow? I still fail to understand how it reproduces in your env.. Can you please include running with `-vvvvv`?

Ah, somehow I thought ```disable_dns``` defaults to ```True```.
Seems like going to ```1.9.5-dev``` fixes the problem.
