### ISSUE TITLE
Add  a module for managing pods

### ISSUE THREAD

**Issue by Luap99** [containers/ansible-podman-collections#51]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

It would be great to add a module for managing pods like the container module.

**Comment by sshnaidm** [comment]
@Luap99 yes, of course. It's the next module I'm gonna make.

**Comment by Luap99** [comment]
Thank you @sshnaidm.
I will test this soon.
