### ISSUE TITLE
bug with load images module version: 1.9.4 : "IndexError: list index out of range"

### ISSUE THREAD

**Issue by bechavod** [containers/ansible-podman-collections#524]
Hi,

there is a bug with 1.9.4 ansible module version. in 1.9.3 it works perfect. 

when I am try to make load images I just this error:

<img width="1422" alt="image" src="https://user-images.githubusercontent.com/53995669/204130894-bf6d10de-2218-40a1-a55e-ec85abde1ae2.png">

It happened on all the docker images files that I am trying to load.

in addition
podman version 4.1.1

**Comment by sshnaidm** [comment]
Please try new 1.10.0 version of podman collection.

**Comment by sshnaidm** [comment]
Feel free to  reopen the issue if it's still the case with 1.10.1 version.
