### ISSUE TITLE
Add some genernal parameters in `containers.podman.podman_play` 

### ISSUE THREAD

**Issue by fsdrw08** [containers/ansible-podman-collections#544]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Describe the results you expected:**
add some genernal parameters in `containers.podman.podman_play` , e.g. `log_opt` and `userns`

**Version of the `containers.podman` collection: 1.10.1**

**Output of `podman version`:**

```
4.3.1
```

**Comment by benblasco** [comment]
I also think this is an important feature.  Adding the ability to pass arbitrary parameters to the command would be helpful to allow the module to keep up with podman development.  Whilst this could break idempotency it would unlock the ability to use all of `podman kube play` features without having to wait for further development of the Ansible collection/module.

**Comment by nishipy** [comment]
I'll work on this and add other options such as `log_opt`
