### ISSUE TITLE
podman_login - does not work in a FIPS environment

### ISSUE THREAD

**Issue by spmfox** [containers/ansible-podman-collections#564]
The following code causes the podman_login module to not work at all in FIPS compliant environments:

``` python
124            checksum = hashlib.md5(content).hexdigest()

139                new_checksum = hashlib.md5(content).hexdigest()
```

error:
```
line 123, in login
ValueError: [digital envelope routines: EVP_DigestInit_ex] disabled for FIPS
```

This can be fixed by changing the hash to something that is allowed in FIPS environments, such as sha256.

**Comment by spmfox** [comment]
I opened a pull request to address this issue:
https://github.com/containers/ansible-podman-collections/pull/566

**Comment by sshnaidm** [comment]
Closed by https://github.com/containers/ansible-podman-collections/pull/566
