### ISSUE TITLE
using digests instead of tags

### ISSUE THREAD

**Issue by avnav88** [containers/ansible-podman-collections#569]
is there a way to have a digest specified when pulling an image:

`FAILED! => {"changed": false, "msg": "Failed to pull image nginx:sha256:2ab30d6ac53580a6db8b657abf0f68d75360ff5cc1670a85acb5bd85ba1b19c0"}`

not sure if this can be done through `extra_args` (also not sure how to use that one, there's no detail in docs)

**Comment by avnav88** [comment]
also wondering if there's a way to use the `podman cp` command to copy files from a container.

**Comment by sshnaidm** [comment]
> also wondering if there's a way to use the `podman cp` command to copy files from a container.

Not yet, please file a separate issue/RFE about it.
