### ISSUE TITLE
podman cp

### ISSUE THREAD

**Issue by avnav0** [containers/ansible-podman-collections#571]
hello, was adviced to create a new issue for a way to use the `podman cp` command to copy files from a container.

use case:

sometimes, i will make a temp container in order to just copy files that i can build off of (usually configs)

```
podman run -d --name nginx.vols nginx:1.23.2
cont_num=$(podman ps -aqf "name=nginx.vols")
podman cp $cont_num:/etc/nginx/. /home/user/volumes/nginx
podman stop nginx.vols && podman rm nginx.vols
```

this would be super useful, since I have to use shell:

```
    - name: 4. copy config files from temp nginx container into volumes dir
      shell: | 
        cont_num=$(podman ps -aqf "name=nginx.vols")
        podman cp $cont_num:/etc/nginx/. /home/user/volumes/nginx
        podman stop nginx.vols && podman rm nginx.vols
      args:
        executable: /bin/bash
```

**Comment by sshnaidm** [comment]
@DilasserT sure, go ahead. I believe it should copy both from and to container?  `containers.podman.podman_copy` is fine.
It's weird docker has only [one way copy module](https://docs.ansible.com/ansible/latest/collections/community/docker/docker_container_copy_into_module.html#ansible-collections-community-docker-docker-container-copy-into-module).

**Comment by DilasserT** [comment]
Yes, I do not see why it should not do both.

**Comment by sshnaidm** [comment]
Done in #813
