### ISSUE TITLE
Browsable docs?

### ISSUE THREAD

**Issue by Yajo** [containers/ansible-podman-collections#59]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

**Steps to reproduce the issue:**

1. Want to know how to use `podman_container`

2. Search for docs.

**Describe the results you received:**
Not found!

**Describe the results you expected:**
Found.

**Additional information you deem important (e.g. issue happens only occasionally):**
Some modules docs can be found in https://docs.ansible.com/ansible/latest/modules/list_of_all_modules.html but are possibly outdated.

**Output of `ansible --version`:**

```
ansible 2.9.9
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/yajo/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.3 (default, May 15 2020, 00:00:00) [GCC 10.1.1 20200507 (Red Hat 10.1.1-1)]
```

**Comment by sshnaidm** [comment]
`podman_container` will be available as part of Ansible 2.10 only.
The documentation of it inside 2.10 is in progress, let's track it in this issue.

**Comment by denysvitali** [comment]
FYI, for now it is possible to read the docs as follows:

```
ansible-doc containers.podman.podman_container.podman_image
```

**Comment by sshnaidm** [comment]
You can see documentation in ansible test docs site for now: http://docs.testing.ansible.com/ansible/2.10/collections/containers/podman/index.html#plugins-in-containers-podman
When 2.10 is out, it will be available in a usual ansible docs site.

**Comment by Yajo** [comment]
That doesn't include docs on `podman_pod`... is that a known issue?

**Comment by sshnaidm** [comment]
@Yajo yeah, it's not up to date.. If you know where I can host docs for now, I'd put them there. It's easy to generate them as @denysvitali wrote above.

**Comment by Yajo** [comment]
One obvious choice is https://readthedocs.org/

**Comment by sshnaidm** [comment]
@Yajo right, but unfortunately I didn't see there option to upload docs, they require `sphinx` build only. And this is not what we have in ansible docs. Or maybe I miss something and it's possible to use `ansible-doc` there?

**Comment by Yajo** [comment]
Oh true. How about GitHub pages then?

**Comment by sshnaidm** [comment]
> Oh true. How about GitHub pages then?

Yep, working on that.
