### ISSUE TITLE
[RFE] New states in podman_volume - `mounted` and `unmounted`

### ISSUE THREAD

**Issue by mskarbek** [containers/ansible-podman-collections#603]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

Alongside `present` and `absent` it would be good to have `mounted` and `unmounted` state which will allow manipulation of the volume content. `mounted` should return path to the volume mount point.

Currently, I'm mounting volumes manually using `ansible.builtin.command` and `podman volume mount` command.

**Comment by sshnaidm** [comment]
@mskarbek please see if #764 helps
