### ISSUE TITLE
Podman volume export module

### ISSUE THREAD

**Issue by DilasserT** [containers/ansible-podman-collections#609]
/kind feature

**Description**

Hi, 

Would it be possible to export volumes with a module similar to `podman_export` ?
Or maybe it should be an additional option to `podman_volume`.

I did not see an option to do this specifically:
`podman volume export myvolume --output myvolume.tar`

I was expecting something like:

```
- containers.podman.podman_volume_export:
    dest: /path/to/myvolume.tar
    volume: myvolume
```

**Comment by sshnaidm** [comment]
I think adding to current `podman_export` would be easier. Want to do a patch?

**Comment by DilasserT** [comment]
I can try. How would you implement it ?

Maybe adding a `volume` field instead of the `container` field, with both fields exclusive ?

```
- containers.podman.podman_export:
    dest: /path/to/myvolume.tar
    volume: myvolume
```

**Comment by sshnaidm** [comment]
I think we can add *in addition* not instead. Both exclusive is fine with me.

**Comment by DilasserT** [comment]
Would it make sense to add the same mechanic to `podman_load` in the same PR ?

**Comment by sshnaidm** [comment]
> Would it make sense to add the same mechanic to `podman_load` in the same PR ?

Yeah, totally.

**Comment by sshnaidm** [comment]
Done in https://github.com/containers/ansible-podman-collections/pull/617
