### ISSUE TITLE
Broken idempotency with device in containers.podman.podman_container

### ISSUE THREAD

**Issue by phicode** [containers/ansible-podman-collections#610]
**Is this a BUG REPORT or FEATURE REQUEST?**

/kind bug

**Description**

Newer versions of `ansible-podman-collection` are no longer idempotent with device passthrough options.

Pull Request [#549](https://github.com/containers/ansible-podman-collections/pull/549), which fixes issue [#537](https://github.com/containers/ansible-podman-collections/issues/537) breaks this idempotency.

Given an ansible playbook using the `containers.podman.podman_container` module with option:
```
device:
  - "/dev/ttyACM0:/dev/zwave:rw"
```
I observe the following change on every playbook run:
```
-devices - ['/dev/ttyACM0:/dev/zwave']
+devices - ['/dev/ttyacm0:/dev/zwave']
```
Reading the initial Issue, I do not see how the provided commit could fix anything.
The `before` list reflects the real devices on the container/host.
Since device names are case-sensitive, the lowercase conversion should be performed on both the
`before` and `after` list, or preferrably none at all.

Removing the line
```
after = [i.lower() for i in after]
```
from [podman_container_lib.py](https://github.com/containers/ansible-podman-collections/blob/9aedda4443ceddea489dd5a650d32855e0e48440/plugins/module_utils/podman/podman_container_lib.py#L875) resolves the problem.
Can Pull Request [#549](https://github.com/containers/ansible-podman-collections/pull/549) be reverted?

**Version of the `containers.podman` collection:**

```
  # https://github.com/containers/ansible-podman-collections
  - name: containers.podman
    version: 1.10.2
    type: galaxy
```

**Output of `ansible --version`:**

```
ansible [core 2.14.8]
  config file = None
  configured module search path = ['/home/phil/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/phil/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.11.4 (main, Jun  7 2023, 10:13:09) [GCC 12.2.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.3.1
API Version:  4.3.1
Go Version:   go1.19.8
Built:        Thu Jan  1 01:00:00 1970
OS/Arch:      linux/amd64
```

**Package info:**

```
podman/testing,now 4.3.1+ds1-8+b1 amd64 [installed]
```

**Regarding podman and symlinks:**

What I can observe from the initial issue [#537](https://github.com/containers/ansible-podman-collections/issues/537) is that the reporter is using symbolic links for the device being passed through. That worked while I was using docker, but it is not working with podman. Podman resolves device symlinks when the container is created, so the idempotency is already broken at that point.

**Comment by sshnaidm** [comment]
@phicode sorry for the confusion. Please check if #611 helps you.

**Comment by sshnaidm** [comment]
> **Regarding podman and symlinks:**
> 
> What I can observe from the initial issue [#537](https://github.com/containers/ansible-podman-collections/issues/537) is that the reporter is using symbolic links for the device being passed through. That worked while I was using docker, but it is not working with podman. Podman resolves device symlinks when the container is created, so the idempotency is already broken at that point.

Then we can use only from `command` from inspection. Probably it's worth to check if we have same devices in https://github.com/containers/ansible-podman-collections/blob/master/plugins/module_utils/podman/podman_container_lib.py#L865 but probably much easier to take `before` from the command.

**Comment by phicode** [comment]
@sshnaidm #611 fixes the problem :+1: 
Thank you
