### ISSUE TITLE
`--build` flag support for Kube Play deployment.

### ISSUE THREAD

**Issue by dzintars** [containers/ansible-podman-collections#633]
/kind feature

**`--build` flag for Kube Play module**

`podman kube play --build deployment.yaml` will "auto-build" the image whose Containerfile is located in the directory alongside `deployment.yaml` and which name matches the image name in the `deployment#containers#image`

```bash
│  └── podman
│     ├── almalinux
│     │  ├── Containerfile
│     │  ├── entrypoint.sh
│     │  └── gerrit.config
│     ├── configmap.yaml
│     ├── deployment.yaml
│     ├── secrets.yaml
│     └── pvc.yaml
```

```yaml
      containers:
        - name: gerrit
          image: almalinux
```

Not sure how well-known is this feature and how important it is.
For sure, you can just do 2 tasks (build and deploy) separately.
But I'm exposing this feature request just because there is such flag for `kube play`.

**Comment by nishipy** [comment]
Hi, I'll work on this.
