### ISSUE TITLE
podman_volume needs to double check name (applies to podman_container, too)

### ISSUE THREAD

**Issue by jessegit** [containers/ansible-podman-collections#661]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

podman_volume wipes other existing volume when unique partial prefix exists.

man podman-volume-inspect says: "Volumes can be queried individually by providing their full name or a unique partial name."

podman_volume does not check that the returned volume name from 'podman volume inspect volume' matches the requested name, hilarity ensues.

Incidentally, the man page is also partially wrong, the match is not made with unique partial name, but unique partial name prefix.

**Steps to reproduce the issue:**

1. verify there are no other volume names starting with 'test'
2. create volume 'test_db' and put some data in it
3. attach volume test_db to a container that is running (optional)
4. try to create volume 'test' with podman_volume

**Describe the results you received:**

Running container:
Error: error removing container 9c9c7f4b1357003bd2bd7bb476a712fae2bf2dbde7c7273bc5dc99f9ae3bff8e that depends on volume test_db: cannot remove container 9c9c7f4b1357003bd2bd7bb476a712fae2bf2dbde7c7273bc5dc99f9ae3bff8e as it is running - running or paused containers cannot be removed without force: container state improper

Non-running container/no container:
volume 'test_db' is removed (and probably volume 'test' created, in my setup the remove fails with an error as each volume root is a separate mountpoint).

**Describe the results you expected:**

new created volume named 'test' without touching volume 'test_db'.

**Version of the `containers.podman` collection:**

```
containers.podman 1.10.3
```

version(s) of all components not relevant.

**Comment by jessegit** [comment]
workaround: when creating volumes or containers, pollute the namespace by adding a postfix that is not used in anywhere else in the names (eg. test_db_prot, test_prot, but *_db would not work).

**Comment by jessegit** [comment]
@sshnaidm Wouldn't it be enough to do the query like now and check the name in the returned data? If the name doesn't match exactly, proceed like the query didn't return anything. (I'm assuming here the check does `podman volume inspect` that does return the name of the real matched volume, not what the query was)

**Comment by sshnaidm** [comment]
@jessegit please check if #684 helps
