### ISSUE TITLE
Add new modules/options for Quadlet

### ISSUE THREAD

**Issue by nishipy** [containers/ansible-podman-collections#671]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

Since Podman 4.7.0, the [`podman generate systemd` command has been deprecated](https://github.com/containers/podman/releases/tag/v4.7.0). Instead of that, it is recommended to use `Quadlet` for running containers and pods under systemd.
Now, it's time to consider adding a new module to support Quadlet to run Podman containers under systemd. 

More specifically, [what we need](https://github.com/containers/ansible-podman-collections/issues/671#issuecomment-1844980619) is:
1. Generation of podman Quadlet files in podman_container (and others) as we have today with generate_systemd.
2. Allow podman_container to generate files only, without creating actually containers. (Need to look how easy to do it with current implementation)

Under question:

3. To check the option to reload systemd in the module as it's suggested here: https://github.com/containers/ansible-podman-collections/pull/585
4. To have podman_generate_quadlet module

**Comment by sshnaidm** [comment]
Yeah, this is a great idea. We need to think how it's better to implement it to avoid problems we have with systemd and its generation.

**Comment by nishipy** [comment]
Quadlet supports some types of units (`[Container]`, `[Kube]`, `[Volume]`, etc.). If we add `podman_container_quadlet`, it might be like the following:
```
- name: Create Quadlet files for container
  podman_container_quadlet:
      description: A minimal container
      image: quay.io/centos/centos:latest
      volume: test.volume:/data
      network: test.network
      exec: sleep 60
      restart: always
      service_spec:
        timeout_start_sec: 900
        exec_start_pre: /usr/share/mincontainer/setup.sh
        wanted_by:
        - multi-user.target
        - default.target
```
Then, this module will create a Quadlet file:
```
[Unit]
Description=A minimal container

[Container]
Image=quay.io/centos/centos:latest
Volume=test.volume:/data
Network=test.network
Exec=sleep 60

[Service]
Restart=always
TimeoutStartSec=900
ExecStartPre=/usr/share/mincontainer/setup.sh

[Install]
WantedBy=multi-user.target default.target
```
After Quadlet files are created, users need to run `systemctl daemon-reload` via `ansible.builtin.systemd_service` module in order to create systemd unit files from Quadlet files.

**Comment by nishipy** [comment]
We can use `ansible.builtin.template` to create Quadlet files with predefined fields, but modules like `podman_container_quadlet` can give more flexibility...

**Comment by nishipy** [comment]
> I think we should add quadlet generation to podman_container, podman_volume, podman_kube_play and podman_network modules

Agreed. This is another option I was thinking of actually. We can add a option  such as `generate_quadlet` with supporting the consistent parameters for `podman run`/`podman kube` as the module.

> Or to have a state generate so the module won't create a container, but only generate files for it.

I see. It looks better than other ideas to me. I think this is easier for users to understand that as you said the module will create not actual Podman resources (containers, networks, volumes, etc) but quadlet files.

**Comment by sshnaidm** [comment]
OK, so let's start summarizing what we need:
1. Generation of podman Quadlet files in podman_container (and others) as we have today with `generate_systemd`.
2. Allow podman_container to generate files only, without creating actually containers. (Need to look how easy to do it with current implementation)

Under question:
3. To check the option to reload systemd in the module as it's suggested here: #585 
4. To have `podman_generate_quadlet` module

**Comment by nishipy** [comment]
Thanks. Can I try prototyping on the 1st one for `podman_container`? 
> Generation of podman Quadlet files in podman_container (and others) as we have today with generate_systemd.

**Comment by nishipy** [comment]
> 2. Allow podman_container to generate files only, without creating actually containers. (Need to look how easy to do it with current implementation

We have the map for each state and method to be executed, so it seems we can add a new state `quadlet` and its method here.

https://github.com/containers/ansible-podman-collections/blob/45893f4a7b5c2ecbd29fc4006d60164e918425c5/plugins/module_utils/podman/podman_container_lib.py#L1744-L1752

> Under question:
> 3. To check the option to reload systemd in the module as it's suggested here: https://github.com/containers/ansible-podman-collections/pull/585

In general cases, I want to use `ansible.builtin.systemd_service`module in order to do `systemctl`-related stuff. However, we always have to run `systemctl daemon-reload` after quadlet file creation, so it sounds reasonable for me to reload systemd in this case.

**Comment by sshnaidm** [comment]
Yeah, as mentioned [here](https://github.com/containers/ansible-podman-collections/pull/585) I'd like to avoid as possible to trigger systemd in these modules, but seems like the Podman is too tied to it and it's pretty unavoidable. @nishipy would you like to see how to do it in a better way? I think we can use the patch of @nogweii and collaborate on it or to make a new one, he has a lot of things prepared already.
I'll look into implementing Quadlet in `common`, that should be usable for all modules, in same way `generate_systemd` is done.

**Comment by nishipy** [comment]
Sorry for my late reply
> @nishipy would you like to see how to do it in a better way?
yes, let me look into this.

**Comment by alorle** [comment]
I am excited about this feature. Has there been any notable progress?

**Comment by sshnaidm** [comment]
I think I've got the initial version for container and network prepared, please review. It currently creates Quadlet file in given folder, using the usual module configuration. It's possible to add required lines using `quadlet_options`, see examples in tests:
```yaml
        quadlet_file_path: /tmp/quadlets/quadlet.container
        quadlet_options:
          - "Label=Test=network"
          - "Label=foo=bar"
```
All not supported in Quadlet options are going to [`PodmanArgs`](https://docs.podman.io/en/latest/markdown/podman-systemd.unit.5.html#podmanargs) section in Quadlet. Some (like `--log-level`) are going to [`GlobalArgs`](https://docs.podman.io/en/latest/markdown/podman-systemd.unit.5.html#globalargs).
Running with `--diff` will print difference in Quadlet configs and also Quadlet config is generated in the end and returned as `podman_quadlet` variable in `results`, like I did with systemd.
```json
"podman_actions": [
"podman run --name container122 --publish 9000:80 --publish 9001:8000 --workdir /bin --env FOO=bar=1 --env BAR=foo --env TEST=1 --env BOOL=False --label somelabel=labelvalue --label otheralbe=othervalue --mount type=devpts,destination=/dev/pts --volume /tmp:/data --detach=True alpine:3.12"
],
    "podman_quadlet": "[Container]\nContainerName=container122\nEnvironment=FOO=bar=1\nEnvironment=BAR=foo\nEnvironment=TEST=1\nEnvironment=BOOL=False\nImage=alpine:3.12\nLabel=somelabel=labelvalue\nLabel=otheralbe=othervalue\nMount=type=devpts,destination=/dev/pts\nPublishPort=9000:80\nPublishPort=9001:8000\nVolume=/tmp:/data\nWorkingDir=/bin\n",
    "podman_systemd": {
        "container-container122": "# container-container122.service\n# autogenerated by Podman 4.8.3\n# Sun Mar  3 18:20:34 IST 2024\n\n[Unit]\nDescription=Podman container-container122.service\nDocumentation=man:podman-generate-systemd(1)\nWants=network-online.target\nAfter=network-online.target\nRequiresMountsFor=/run/user/1000/containers\n\n[Service]\nEnvironment=PODMAN_SYSTEMD_UNIT=%n\nRestart=on-failure\nTimeoutStopSec=70\nExecStart=/usr/bin/podman start container122\nExecStop=/usr/bin/podman stop  \\\n\t-t 10 container122\nExecStopPost=/usr/bin/podman stop  \\\n\t-t 10 container122\nPIDFile=/run/user/1000/containers/overlay-containers/c3d91cde84ed953392e22532e3c168466a24a657262869c84d7c4650d4413892/userdata/conmon.pid\nType=forking\n\n[Install]\nWantedBy=default.target\n"
}
```
Please review and comment, what else is required and desirable?
Systemd reload is not implemented yet, will be the next step I suppose.

**Comment by sshnaidm** [comment]
Added support for Pod as well

**Comment by alorle** [comment]
Great news @sshnaidm !! Firstly, thanks for the effort. I would like to test this, so I can give you some feedback if you want, but I don't know how. Could you point me to the documentation to be able to install your branch into my Ansible project?

**Comment by sshnaidm** [comment]
I wonder if we need to add the generation of systemd unit file themselves, or to leave it to `systemd daemon-reload` to do.
It's possible by running `/usr/libexec/podman/quadlet` (one of [systemd generators](https://www.freedesktop.org/software/systemd/man/latest/systemd.generator.html)) like: `QUADLET_UNIT_DIRS=<Directory> /usr/lib/systemd/system-generators/podman-system-generator {--user} --dryrun` ([docs](https://docs.podman.io/en/latest/markdown/podman-systemd.unit.5.html#debugging-unit-files)) . Seems like it can generate only all files in a dir, not one by one, so I doubt it has any value in this module.

**Comment by nishipy** [comment]
That is certainly true. The `/usr/libexec/podman/quadlet` will be run for all files in [specific directories](https://docs.podman.io/en/latest/markdown/podman-systemd.unit.5.html#podman-unit-search-path) when `systemctl daemon-reload` (and during boot).
I think in order to generate regular sysmtemd unit files, it would be better to run `systemctl daemon-relaod` by include it in this module or by using `ansible.builtin.systemd_service` module. Considering the point @sshnaidm mentioned (i.e. `/usr/libexec/podman/quadlet` will search all files in directories and we cannot give a specific file), it might be clearer to ask users to add `ansible.builtin.systemd_service` after tasks with this module.

**Comment by alorle** [comment]
I've been testing it this week and it works perfectly. Thanks for the effort!!

**Comment by nishipy** [comment]
> I think in order to generate regular sysmtemd unit files, it would be better to run `systemctl daemon-relaod` by include it in this module or by using `ansible.builtin.systemd_service` module. Considering the point @sshnaidm mentioned (i.e. `/usr/libexec/podman/quadlet` will search all files in directories and we cannot give a specific file), it might be clearer to ask users to add `ansible.builtin.systemd_service` after tasks with this module.

Or, how about adding a parameter like `daemon_reload` (default: false) so that users can switch whether to execute daemon-reload or not.
