### ISSUE TITLE
Alias parameters "stop_timeout" and "time" for podman generate systemd

### ISSUE THREAD

**Issue by fuljo** [containers/ansible-podman-collections#683]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

The problem involves the `systemd` part of module `podman_container`.
If using Podman version < 4 (e.g. from Ubuntu 22.04 LTS), parameter `stop_timeout` is not supported in `podman generate systemd`.
This was already present in v3, but it was named `time`, which is also a module parameter.

My proposal is to make `stop_timeout` and `time` aliases, so that:
- either parameter (but not both) can be specified in the Ansible task
- the parameter name fed to `podman generate systemd` is selected based on the detected Podman version

**Version of the `containers.podman` collection:** 
**Either git commit if installed from git: `git show --summary`**
**Or version from `ansible-galaxy` if installed from galaxy: `ansible-galaxy collection list | grep containers.podman`**

```
commit edcb13dd8aff5959c98f25bafa9fda8e14a9dbc3
Author: Sergey <6213510+sshnaidm@users.noreply.github.com>
Date:   Thu Nov 30 16:04:51 2023 +0200

    Fail if systemd generation failed and it's explicitly set (#682)
```

**Output of `ansible --version`:**

```
ansible [core 2.16.0]
```

**Comment by fuljo** [comment]
I'm already testing a prototype of this. Will update if everything is fine.
If the behavior is desirable, I will open a PR.

**Comment by sshnaidm** [comment]
@fuljo sure, feel free to open
