### ISSUE TITLE
podman_container: support for "--pull" option 

### ISSUE THREAD

**Issue by MaikiGirardi** [containers/ansible-podman-collections#738]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

On containers.podman.podman_container module there is no option for `--pull` , this is relevant for horizontal scaling custom image build.

<https://docs.podman.io/en/latest/markdown/podman-run.1.html#pull-policy>

**Comment by sshnaidm** [comment]
@alive1 you can use `force: true` to pull image always.

**Comment by sshnaidm** [comment]
@alive1 fixed in #750
