### ISSUE TITLE
quadlet creates wrong healthcheck command for container

### ISSUE THREAD

**Issue by Marwel** [containers/ansible-podman-collections#747]
/kind bug

**Description**

https://github.com/containers/ansible-podman-collections/blob/1ffa40c70593c251ba8ea79836579bc356841be6/plugins/module_utils/podman/quadlet.py#L91

HealthCheckCmd is not a valid command for podman/quadlet
as can be seen
https://github.com/containers/podman/blob/34d2d20d46c1ad3cf13432fc481047f1b285ff20/pkg/systemd/quadlet/quadlet.go#L86

**Steps to reproduce the issue:**

1. Try to deploy a container via quadlet with a healthcheck defined

**Describe the results you received:**
quadlet -dryrun then gives the following error
quadlet-generator[12345]: converting "example_app.container": unsupported key 'HealthCheckCmd' in group 'Container' in /etc/containers/systemd/example_app.container

**Describe the results you expected:**

A working quadlet definition with "HealthCmd" instead of "HealthCheckCmd"

**Comment by sshnaidm** [comment]
fixed by #748
