### ISSUE TITLE
Issues pulling images with similar tags (cannot pull one with a shorter left substring than a pre-existing image) - See 736

### ISSUE THREAD

**Issue by bar0n36** [containers/ansible-podman-collections#831]
Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)

/kind bug

**Description**

RELOGGING 736 as it had the information in. Podman version on the host is 3.3.1 as per issue 736

When attempting to pull an image with a tag that is a left substring of a pre-existing image using containers.podman.podman_image, the image pull operation fails and returns Error: error inspecting object: no such object.

**Steps to reproduce the issue**:

Run the below playbook:
```- hosts: target
become: true
gather_facts: true

tasks:
- name: Pull RabbitMQ Image - Management
containers.podman.podman_image:
name: rabbitmq
tag: 3.12-management
become: true
become_user: "usera"

- name: Pull RabbitMQ Image - Standard
  containers.podman.podman_image:
    name: rabbitmq
    tag: 3.12
  become: true
  become_user: "usera"`
Describe the results you received:
PLAY [target] *****************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] *****************************************************************************************************************************************************************************************************************************
ok: [target]

TASK [Pull RabbitMQ Image - Management] ************************************************************************************************************************************************************************************************************
ok: [target]

TASK [Pull RabbitMQ Image - Standard] **************************************************************************************************************************************************************************************************************
fatal: [target]: FAILED! => {"changed": false, "msg": "Failed to run ['/bin/podman', 'inspect', 'rabbitmq:3.12', '--format', 'json'] ['inspect', 'rabbitmq:3.12', '--format', 'json']: Error: error inspecting object: no such object: "rabbitmq:3.12"\n"}
```

**Describe the results you expected**:
I would expect both images to be pulled successfully.
If I remove the first image and then just run the second task, it works as expected. It appears to be an issue with it failing to differentiate between the tags '3.12-management' and '3.12' on whether to pull or not.

**Additional information you deem important (e.g. issue happens only occasionally):**
I have been able to replicate this consistently with a couple of different images using the collection v1.12.0 and v1.13.0
**UPDATE: Affects collection 1.15.4  as well and newer Ansible and Python versions**

**Version of the containers.podman collection**:
 v1.15.4  - installed from Ansible Galaxy

**Output of ansible --version:**
`ansible [core 2.17.2]
python v 3.11.2`

**Output of podman version:**
`3.3.1 - I have confirmed that I can perform this task successfully using podman commands natively, so not a podman issue.`

**Comment by sshnaidm** [comment]
Well, it's because of behavior of Podman 3.3.1 in this case, it searches for substring:
```
$ /home/sshnaidm/go/podmans/3.3.1/podman image ls rabbitmq:3.12
REPOSITORY                  TAG              IMAGE ID      CREATED        SIZE
docker.io/library/rabbitmq  3.12-management  fb25daa8bca5  15 months ago  254 MB
```
It changed in Podman v4:
```
$ /home/sshnaidm/go/podmans/4.0.1/podman image ls rabbitmq:3.12
REPOSITORY  TAG         IMAGE ID    CREATED     SIZE
```
And because now it's Podman v5 and v3 is very old, I don't think we can do much here. It's better to upgrade at least to v4.

**Comment by sshnaidm** [comment]
Actually it seems like an easy step, hopefully not breaking anything. Please check if #832 solves it

**Comment by bar0n36** [comment]
@sshnaidm - Thanks. Yes. Podman version is ancient, but I don't know whether the upgrade will fix it (I'm currently stuck on v3 in production) as the podman CLI does not have the problem.
