### ISSUE TITLE
Podman login should support secret option

### ISSUE THREAD

**Issue by mhjacks** [containers/ansible-podman-collections#859]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

Podman has supported using secrets to login to registries since 4.7.0. The podman_login module should support this.

See #858 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version of the `containers.podman` collection:** 1.16.1

**Comment by sshnaidm** [comment]
Fixed in https://github.com/containers/ansible-podman-collections/pull/858
