### ISSUE TITLE
Add option to define quadlet file permission

### ISSUE THREAD

**Issue by ghoudmon** [containers/ansible-podman-collections#864]
/kind feature

**Description**

Quadlet files are created with the `0644` permission, which allows all users to read the quadlet file.
This can lead to security issues. For example, if sensitive information is defined in environment variables, it will be visible to all users.
Currently, an additional task is required to set more restrictive permissions on the generated files.

As a user, it would be nice to have an option to specify the mode of the quadlet file, for example `quadlet_file_m̀ode`.
And I suggest setting it to `0640` by default.

**Comment by sshnaidm** [comment]
Great idea, would you like to submit a patch to do it?

**Comment by ghoudmon** [comment]
Hello, 

I submit the patch, with a little diffrence with my first mind: `0640` is the default permission if the quadlet doesn't exist. If the qualdet file exist, it doesn't change the permission.
It's to keep idempotence with previously created quadlet files.
