### ISSUE TITLE
podman_container doesn't support the use of .image-files when creating quadlets

### ISSUE THREAD

**Issue by HassoSigbjoernson** [containers/ansible-podman-collections#871]
Creating a container-quatlet works as expected when I directly specify the image.

```
containers.podman.podman_container:
  image: "docker.io/library/httpd:alpine"
```

 But when I try to move that into a seperate quadlet file I get an error:

```
containers.podman.podman_container:
  image: "httpd.image"
```

**Error Message**
```
FAILED! => {"changed": false, "msg": "Can't pull image httpd.image", "stderr": "Error: short-name resolution enforced but cannot prompt without a TTY\n", "stderr_lines": ["Error: short-name resolution enforced but cannot prompt without a TTY"], "stdout": "", "stdout_lines": []}
```

So I assume the short-name resolution needs an exception for images ending in ".image" to make that work.

**Comment by sshnaidm** [comment]
@HassoSigbjoernson please paste the full task, not only image, thanks.

**Comment by sshnaidm** [comment]
@HassoSigbjoernson please check if #872 solves it.
