### ISSUE TITLE
Documentation improvement on network property for podman_container

### ISSUE THREAD

**Issue by vkhashimoto** [containers/ansible-podman-collections#877]
/kind feature

**Description**
While looking for the `network` property on `podman_container` module, it's difficult to determine what values can be used for the property.

**Steps to reproduce the issue:**

1. Access the documentation for [podman_container module](https://galaxy.ansible.com/ui/repo/published/containers/podman/content/module/podman_container/);

2. Check the `network` parameter;

**Describe the results you received:**
In Galaxy, the comments are like this: ![Image](https://github.com/user-attachments/assets/af90e435-a5e3-4b49-ad8d-68911997248b)
Running the docs locally (`main` branch | `bash -xe contrib/build_docs.sh`): ![Image](https://github.com/user-attachments/assets/7ea5651e-c382-4cc9-9a3f-80257cec07f6)

**Describe the results you expected:**
I've made this changes, following the patterns from the `state` property: ![Image](https://github.com/user-attachments/assets/f34a65dd-ad04-4568-a039-661418c1fc50)

If it's ok, I can open a PR with my changes. I don't know how to generate a local copy of the galaxy to validate the text.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version of the `containers.podman` collection:** N/A
**Either git commit if installed from git: `git show --summary`** N/A
**Or version from `ansible-galaxy` if installed from galaxy: `ansible-galaxy collection list | grep containers.podman`** N/A

**Output of `ansible --version`:** N/A

**Output of `podman version`:** N/A

**Output of `podman info --debug`:** N/A

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):** N/A

**Playbok you run with ansible (e.g. content of `playbook.yaml`):** N/A

**Command line and output of ansible run with high verbosity** N/A

**Please NOTE: if you submit a bug about idempotency, run the playbook with `--diff` option, like:** N/A

**Additional environment details (AWS, VirtualBox, physical, etc.):** N/A

**PS:** GitHub didn't insert the issue template when creating this issue. When opening the template file, it gave me this warning. I don't know if they're related
![Image](https://github.com/user-attachments/assets/694eb838-4d8d-4ab0-9d1f-5e6337f5e484)

**Comment by sshnaidm** [comment]
I'll take care of issue templates, it's not related to you.
Please open a PR, I'll run the docs locally to check it. Thanks!
