### ISSUE TITLE
podman_container: cannot declare multiple dns search domains

### ISSUE THREAD

**Issue by u6062276-ethanwoods** [containers/ansible-podman-collections#880]
Is there a reason that multiple dns search domains are supported under podman_pod but not podman_container? Does the inclusion of the alias "dns_search_domains" for this parameter not suggest that it is intended to support a list of values?

I couldn't find any previous discussion on this so forgive me if I'm missing something here.

**Comment by sshnaidm** [comment]
You can always specify them with comma separated: `dns_search: domain.com,domain2.com,domain3.com`. There is no specific reason to have it different, you can submit an issue. Or to propose a patch to improve it 😄
